name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup Playwright
      run: |
        dotnet tool install -g Microsoft.Playwright.CLI
        npx playwright install-deps chromium
    # note this step is needed because the latest chromium is not being installed with the above commands
    - name: Ensure latest Chromium
      run: |
        npm i -D playwright
    - name: Test
      run: dotnet test ./tests/PlaywrightContrib.Tests --no-build --verbosity normal
