name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup Playwright
      run: pwsh ./tests/PlaywrightContrib.Tests/bin/Debug/net8.0/playwright.ps1 install
    - name: Test
      run: dotnet test ./tests/PlaywrightContrib.Tests --no-build --verbosity normal
